import type { VariableCategory } from "./types"

// Default variable categories used by both full and mini expression editors
export const defaultVariableCategories: VariableCategory[] = [
  {
    name: "Item & Loop",
    icon: "repeat",
    items: [
      { label: "$itemIndex", type: "variable", description: "Current item index (0-based)", insertText: "$itemIndex" },
      {
        label: "$itemIndex + 1",
        type: "variable",
        description: "Current item number (1-based)",
        insertText: "$itemIndex + 1",
      },
    ],
  },
  {
    name: "Node Helpers",
    icon: "check-circle",
    items: [
      {
        label: "isExecuted()",
        type: "method",
        description: "Check if node has executed",
        insertText: 'isExecuted("")',
      },
      {
        label: "hasData()",
        type: "method",
        description: "Check if node has non-empty data",
        insertText: 'hasData("")',
      },
      {
        label: "getNodeData()",
        type: "method",
        description: "Get node data with fallback",
        insertText: 'getNodeData("", null)',
      },
      {
        label: "firstExecuted()",
        type: "method",
        description: "Get first executed node from list",
        insertText: 'firstExecuted(["", ""])',
      },
    ],
  },
  {
    name: "Date & Time",
    icon: "calendar",
    items: [
      { label: "$now", type: "variable", description: "Current timestamp", insertText: "$now" },
      { label: "$today", type: "variable", description: "Current date", insertText: "$today" },
      { label: "DateTime.now()", type: "method", description: "Luxon DateTime", insertText: "DateTime.now()" },
      {
        label: "DateTime.fromISO()",
        type: "method",
        description: "Parse ISO string",
        insertText: 'DateTime.fromISO("")',
      },
    ],
  },
  {
    name: "String Methods",
    icon: "function",
    items: [
      { label: ".toUpperCase()", type: "method", description: "Convert to UPPERCASE", insertText: ".toUpperCase()" },
      { label: ".toLowerCase()", type: "method", description: "Convert to lowercase", insertText: ".toLowerCase()" },
      { label: ".trim()", type: "method", description: "Remove whitespace both ends", insertText: ".trim()" },
      { label: ".trimStart()", type: "method", description: "Remove leading whitespace", insertText: ".trimStart()" },
      { label: ".trimEnd()", type: "method", description: "Remove trailing whitespace", insertText: ".trimEnd()" },
      {
        label: ".padStart()",
        type: "method",
        description: 'Pad start: "5".padStart(3,"0")',
        insertText: '.padStart(2, "0")',
      },
      { label: ".padEnd()", type: "method", description: 'Pad end: "5".padEnd(3,"0")', insertText: '.padEnd(2, "0")' },
      { label: ".includes()", type: "method", description: "Check if contains substring", insertText: '.includes("")' },
      { label: ".startsWith()", type: "method", description: "Check if starts with", insertText: '.startsWith("")' },
      { label: ".endsWith()", type: "method", description: "Check if ends with", insertText: '.endsWith("")' },
      { label: ".indexOf()", type: "method", description: "Find first index of substring", insertText: '.indexOf("")' },
      {
        label: ".slice()",
        type: "method",
        description: "Extract portion: str.slice(0, 5)",
        insertText: ".slice(0, 5)",
      },
      { label: ".substring()", type: "method", description: "Extract between indices", insertText: ".substring(0, 5)" },
      { label: ".charAt()", type: "method", description: "Get character at index", insertText: ".charAt(0)" },
      { label: ".at()", type: "method", description: "Get char at index (-1 for last)", insertText: ".at(-1)" },
      { label: ".split()", type: "method", description: "Split into array", insertText: '.split("")' },
      { label: ".replace()", type: "method", description: "Replace first match", insertText: '.replace("old", "new")' },
      {
        label: ".replaceAll()",
        type: "method",
        description: "Replace all matches",
        insertText: '.replaceAll("old", "new")',
      },
      { label: ".repeat()", type: "method", description: "Repeat string n times", insertText: ".repeat(3)" },
      { label: ".length", type: "property", description: "Get string length", insertText: ".length" },
      { label: ".concat()", type: "method", description: "Concatenate strings", insertText: '.concat(" ", "text")' },
    ],
  },
  {
    name: "Array Methods",
    icon: "function",
    items: [
      { label: ".map()", type: "method", description: "Transform each element", insertText: ".map(item => item)" },
      { label: ".filter()", type: "method", description: "Filter elements", insertText: ".filter(item => item)" },
      {
        label: ".reduce()",
        type: "method",
        description: "Reduce to single value",
        insertText: ".reduce((acc, item) => acc + item, 0)",
      },
      {
        label: ".find()",
        type: "method",
        description: "Find first matching element",
        insertText: ".find(item => item)",
      },
      {
        label: ".findIndex()",
        type: "method",
        description: "Find index of first match",
        insertText: ".findIndex(item => item)",
      },
      {
        label: ".includes()",
        type: "method",
        description: "Check if contains element",
        insertText: ".includes(value)",
      },
      {
        label: ".indexOf()",
        type: "method",
        description: "Find first index of element",
        insertText: ".indexOf(value)",
      },
      {
        label: ".some()",
        type: "method",
        description: "Test if any element passes",
        insertText: ".some(item => item)",
      },
      {
        label: ".every()",
        type: "method",
        description: "Test if all elements pass",
        insertText: ".every(item => item)",
      },
      { label: ".sort()", type: "method", description: "Sort elements", insertText: ".sort((a, b) => a - b)" },
      { label: ".reverse()", type: "method", description: "Reverse array", insertText: ".reverse()" },
      { label: ".slice()", type: "method", description: "Extract portion", insertText: ".slice(0, 5)" },
      { label: ".concat()", type: "method", description: "Merge arrays", insertText: ".concat([])" },
      { label: ".join()", type: "method", description: "Join to string", insertText: '.join(", ")' },
      { label: ".flat()", type: "method", description: "Flatten nested arrays", insertText: ".flat()" },
      { label: ".flatMap()", type: "method", description: "Map then flatten", insertText: ".flatMap(item => [item])" },
      { label: ".at()", type: "method", description: "Get element at index", insertText: ".at(-1)" },
      { label: ".push()", type: "method", description: "Add to end", insertText: ".push(value)" },
      { label: ".pop()", type: "method", description: "Remove from end", insertText: ".pop()" },
      { label: ".shift()", type: "method", description: "Remove from start", insertText: ".shift()" },
      { label: ".unshift()", type: "method", description: "Add to start", insertText: ".unshift(value)" },
      { label: ".length", type: "property", description: "Get array length", insertText: ".length" },
    ],
  },
  {
    name: "Number & Math",
    icon: "function",
    items: [
      { label: ".toFixed()", type: "method", description: "Format to fixed decimals", insertText: ".toFixed(2)" },
      { label: ".toString()", type: "method", description: "Convert to string", insertText: ".toString()" },
      { label: "Math.round()", type: "method", description: "Round to nearest integer", insertText: "Math.round()" },
      { label: "Math.floor()", type: "method", description: "Round down", insertText: "Math.floor()" },
      { label: "Math.ceil()", type: "method", description: "Round up", insertText: "Math.ceil()" },
      { label: "Math.abs()", type: "method", description: "Absolute value", insertText: "Math.abs()" },
      { label: "Math.min()", type: "method", description: "Minimum value", insertText: "Math.min()" },
      { label: "Math.max()", type: "method", description: "Maximum value", insertText: "Math.max()" },
      { label: "Math.random()", type: "method", description: "Random 0-1", insertText: "Math.random()" },
      { label: "Number()", type: "method", description: "Convert to number", insertText: "Number()" },
      { label: "parseInt()", type: "method", description: "Parse integer", insertText: "parseInt()" },
      { label: "parseFloat()", type: "method", description: "Parse float", insertText: "parseFloat()" },
    ],
  },
  {
    name: "Object Methods",
    icon: "function",
    items: [
      { label: "Object.keys()", type: "method", description: "Get object keys", insertText: "Object.keys()" },
      { label: "Object.values()", type: "method", description: "Get object values", insertText: "Object.values()" },
      {
        label: "Object.entries()",
        type: "method",
        description: "Get [key, value] pairs",
        insertText: "Object.entries()",
      },
      { label: "Object.assign()", type: "method", description: "Merge objects", insertText: "Object.assign({}, obj)" },
    ],
  },
  {
    name: "JSON Methods",
    icon: "function",
    items: [
      {
        label: "JSON.stringify()",
        type: "method",
        description: "Convert to JSON string",
        insertText: "JSON.stringify()",
      },
      { label: "JSON.parse()", type: "method", description: "Parse JSON string", insertText: "JSON.parse()" },
    ],
  },
]
